"use strict";
/*
 * Copyright 2023 Sony Semiconductor Solutions Corp. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.SmartCamera = void 0;
/**
 * @enum {number}
 */
var SmartCamera;
(function (SmartCamera) {
    var BoundingBox;
    (function (BoundingBox) {
        BoundingBox[BoundingBox["NONE"] = 0] = "NONE";
        BoundingBox[BoundingBox["BoundingBox2d"] = 1] = "BoundingBox2d";
    })(BoundingBox = SmartCamera.BoundingBox || (SmartCamera.BoundingBox = {}));
})(SmartCamera = exports.SmartCamera || (exports.SmartCamera = {}));
;
/**
 * @constructor
 */
(function (SmartCamera) {
    var BoundingBox2d = /** @class */ (function () {
        function BoundingBox2d() {
            this.bb = null;
            this.bb_pos = 0;
        }
        /**
       * @param number i
       * @param flatbuffers.ByteBuffer bb
       * @returns BoundingBox2d
       */
        BoundingBox2d.prototype.__init = function (i, bb) {
            this.bb_pos = i;
            this.bb = bb;
            return this;
        };
        ;
        /**
       * @param flatbuffers.ByteBuffer bb
       * @param BoundingBox2d= obj
       * @returns BoundingBox2d
       */
        BoundingBox2d.getRootAsBoundingBox2d = function (bb, obj) {
            return (obj || new BoundingBox2d()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
        };
        ;
        /**
       * @returns number
       */
        BoundingBox2d.prototype.left = function () {
            var offset = this.bb.__offset(this.bb_pos, 4);
            return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
        };
        ;
        /**
       * @returns number
       */
        BoundingBox2d.prototype.top = function () {
            var offset = this.bb.__offset(this.bb_pos, 6);
            return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
        };
        ;
        /**
       * @returns number
       */
        BoundingBox2d.prototype.right = function () {
            var offset = this.bb.__offset(this.bb_pos, 8);
            return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
        };
        ;
        /**
       * @returns number
       */
        BoundingBox2d.prototype.bottom = function () {
            var offset = this.bb.__offset(this.bb_pos, 10);
            return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       */
        BoundingBox2d.startBoundingBox2d = function (builder) {
            builder.startObject(4);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param number left
       */
        BoundingBox2d.addLeft = function (builder, left) {
            builder.addFieldInt32(0, left, 0);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param number top
       */
        BoundingBox2d.addTop = function (builder, top) {
            builder.addFieldInt32(1, top, 0);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param number right
       */
        BoundingBox2d.addRight = function (builder, right) {
            builder.addFieldInt32(2, right, 0);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param number bottom
       */
        BoundingBox2d.addBottom = function (builder, bottom) {
            builder.addFieldInt32(3, bottom, 0);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @returns flatbuffers.Offset
       */
        BoundingBox2d.endBoundingBox2d = function (builder) {
            var offset = builder.endObject();
            return offset;
        };
        ;
        BoundingBox2d.createBoundingBox2d = function (builder, left, top, right, bottom) {
            BoundingBox2d.startBoundingBox2d(builder);
            BoundingBox2d.addLeft(builder, left);
            BoundingBox2d.addTop(builder, top);
            BoundingBox2d.addRight(builder, right);
            BoundingBox2d.addBottom(builder, bottom);
            return BoundingBox2d.endBoundingBox2d(builder);
        };
        return BoundingBox2d;
    }());
    SmartCamera.BoundingBox2d = BoundingBox2d;
})(SmartCamera = exports.SmartCamera || (exports.SmartCamera = {}));
/**
 * @constructor
 */
(function (SmartCamera) {
    var GeneralObject = /** @class */ (function () {
        function GeneralObject() {
            this.bb = null;
            this.bb_pos = 0;
        }
        /**
       * @param number i
       * @param flatbuffers.ByteBuffer bb
       * @returns GeneralObject
       */
        GeneralObject.prototype.__init = function (i, bb) {
            this.bb_pos = i;
            this.bb = bb;
            return this;
        };
        ;
        /**
       * @param flatbuffers.ByteBuffer bb
       * @param GeneralObject= obj
       * @returns GeneralObject
       */
        GeneralObject.getRootAsGeneralObject = function (bb, obj) {
            return (obj || new GeneralObject()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
        };
        ;
        /**
       * @returns number
       */
        GeneralObject.prototype.classId = function () {
            var offset = this.bb.__offset(this.bb_pos, 4);
            return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
        };
        ;
        /**
       * @returns SmartCamera.BoundingBox
       */
        GeneralObject.prototype.boundingBoxType = function () {
            var offset = this.bb.__offset(this.bb_pos, 6);
            return offset ? /**  */ (this.bb.readUint8(this.bb_pos + offset)) : SmartCamera.BoundingBox.NONE;
        };
        ;
        /**
       * @param flatbuffers.Table obj
       * @returns ?flatbuffers.Table
       */
        GeneralObject.prototype.boundingBox = function (obj) {
            var offset = this.bb.__offset(this.bb_pos, 8);
            return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
        };
        ;
        /**
       * @returns number
       */
        GeneralObject.prototype.score = function () {
            var offset = this.bb.__offset(this.bb_pos, 10);
            return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       */
        GeneralObject.startGeneralObject = function (builder) {
            builder.startObject(4);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param number classId
       */
        GeneralObject.addClassId = function (builder, classId) {
            builder.addFieldInt32(0, classId, 0);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param SmartCamera.BoundingBox boundingBoxType
       */
        GeneralObject.addBoundingBoxType = function (builder, boundingBoxType) {
            builder.addFieldInt8(1, boundingBoxType, SmartCamera.BoundingBox.NONE);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param flatbuffers.Offset boundingBoxOffset
       */
        GeneralObject.addBoundingBox = function (builder, boundingBoxOffset) {
            builder.addFieldOffset(2, boundingBoxOffset, 0);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param number score
       */
        GeneralObject.addScore = function (builder, score) {
            builder.addFieldFloat32(3, score, 0.0);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @returns flatbuffers.Offset
       */
        GeneralObject.endGeneralObject = function (builder) {
            var offset = builder.endObject();
            return offset;
        };
        ;
        GeneralObject.createGeneralObject = function (builder, classId, boundingBoxType, boundingBoxOffset, score) {
            GeneralObject.startGeneralObject(builder);
            GeneralObject.addClassId(builder, classId);
            GeneralObject.addBoundingBoxType(builder, boundingBoxType);
            GeneralObject.addBoundingBox(builder, boundingBoxOffset);
            GeneralObject.addScore(builder, score);
            return GeneralObject.endGeneralObject(builder);
        };
        return GeneralObject;
    }());
    SmartCamera.GeneralObject = GeneralObject;
})(SmartCamera = exports.SmartCamera || (exports.SmartCamera = {}));
/**
 * @constructor
 */
(function (SmartCamera) {
    var ObjectDetectionData = /** @class */ (function () {
        function ObjectDetectionData() {
            this.bb = null;
            this.bb_pos = 0;
        }
        /**
       * @param number i
       * @param flatbuffers.ByteBuffer bb
       * @returns ObjectDetectionData
       */
        ObjectDetectionData.prototype.__init = function (i, bb) {
            this.bb_pos = i;
            this.bb = bb;
            return this;
        };
        ;
        /**
       * @param flatbuffers.ByteBuffer bb
       * @param ObjectDetectionData= obj
       * @returns ObjectDetectionData
       */
        ObjectDetectionData.getRootAsObjectDetectionData = function (bb, obj) {
            return (obj || new ObjectDetectionData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
        };
        ;
        /**
       * @param number index
       * @param SmartCamera.GeneralObject= obj
       * @returns SmartCamera.GeneralObject
       */
        ObjectDetectionData.prototype.objectDetectionList = function (index, obj) {
            var offset = this.bb.__offset(this.bb_pos, 4);
            return offset ? (obj || new SmartCamera.GeneralObject()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
        };
        ;
        /**
       * @returns number
       */
        ObjectDetectionData.prototype.objectDetectionListLength = function () {
            var offset = this.bb.__offset(this.bb_pos, 4);
            return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       */
        ObjectDetectionData.startObjectDetectionData = function (builder) {
            builder.startObject(1);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param flatbuffers.Offset objectDetectionListOffset
       */
        ObjectDetectionData.addObjectDetectionList = function (builder, objectDetectionListOffset) {
            builder.addFieldOffset(0, objectDetectionListOffset, 0);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param Array.<flatbuffers.Offset> data
       * @returns flatbuffers.Offset
       */
        ObjectDetectionData.createObjectDetectionListVector = function (builder, data) {
            builder.startVector(4, data.length, 4);
            for (var i = data.length - 1; i >= 0; i--) {
                builder.addOffset(data[i]);
            }
            return builder.endVector();
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param number numElems
       */
        ObjectDetectionData.startObjectDetectionListVector = function (builder, numElems) {
            builder.startVector(4, numElems, 4);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @returns flatbuffers.Offset
       */
        ObjectDetectionData.endObjectDetectionData = function (builder) {
            var offset = builder.endObject();
            return offset;
        };
        ;
        ObjectDetectionData.createObjectDetectionData = function (builder, objectDetectionListOffset) {
            ObjectDetectionData.startObjectDetectionData(builder);
            ObjectDetectionData.addObjectDetectionList(builder, objectDetectionListOffset);
            return ObjectDetectionData.endObjectDetectionData(builder);
        };
        return ObjectDetectionData;
    }());
    SmartCamera.ObjectDetectionData = ObjectDetectionData;
})(SmartCamera = exports.SmartCamera || (exports.SmartCamera = {}));
/**
 * @constructor
 */
(function (SmartCamera) {
    var ObjectDetectionTop = /** @class */ (function () {
        function ObjectDetectionTop() {
            this.bb = null;
            this.bb_pos = 0;
        }
        /**
       * @param number i
       * @param flatbuffers.ByteBuffer bb
       * @returns ObjectDetectionTop
       */
        ObjectDetectionTop.prototype.__init = function (i, bb) {
            this.bb_pos = i;
            this.bb = bb;
            return this;
        };
        ;
        /**
       * @param flatbuffers.ByteBuffer bb
       * @param ObjectDetectionTop= obj
       * @returns ObjectDetectionTop
       */
        ObjectDetectionTop.getRootAsObjectDetectionTop = function (bb, obj) {
            return (obj || new ObjectDetectionTop()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
        };
        ;
        /**
       * @param SmartCamera.ObjectDetectionData= obj
       * @returns SmartCamera.ObjectDetectionData|null
       */
        ObjectDetectionTop.prototype.perception = function (obj) {
            var offset = this.bb.__offset(this.bb_pos, 4);
            return offset ? (obj || new SmartCamera.ObjectDetectionData()).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       */
        ObjectDetectionTop.startObjectDetectionTop = function (builder) {
            builder.startObject(1);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param flatbuffers.Offset perceptionOffset
       */
        ObjectDetectionTop.addPerception = function (builder, perceptionOffset) {
            builder.addFieldOffset(0, perceptionOffset, 0);
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @returns flatbuffers.Offset
       */
        ObjectDetectionTop.endObjectDetectionTop = function (builder) {
            var offset = builder.endObject();
            return offset;
        };
        ;
        /**
       * @param flatbuffers.Builder builder
       * @param flatbuffers.Offset offset
       */
        ObjectDetectionTop.finishObjectDetectionTopBuffer = function (builder, offset) {
            builder.finish(offset);
        };
        ;
        ObjectDetectionTop.createObjectDetectionTop = function (builder, perceptionOffset) {
            ObjectDetectionTop.startObjectDetectionTop(builder);
            ObjectDetectionTop.addPerception(builder, perceptionOffset);
            return ObjectDetectionTop.endObjectDetectionTop(builder);
        };
        return ObjectDetectionTop;
    }());
    SmartCamera.ObjectDetectionTop = ObjectDetectionTop;
})(SmartCamera = exports.SmartCamera || (exports.SmartCamera = {}));
