"use strict";
/*
 * Copyright 2023 Sony Semiconductor Solutions Corp. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.unionListToBoundingBox = exports.unionToBoundingBox = exports.BoundingBox = void 0;
var bounding_box2d_1 = require("./bounding-box2d");
var BoundingBox;
(function (BoundingBox) {
    BoundingBox[BoundingBox["NONE"] = 0] = "NONE";
    BoundingBox[BoundingBox["BoundingBox2d"] = 1] = "BoundingBox2d";
})(BoundingBox = exports.BoundingBox || (exports.BoundingBox = {}));
function unionToBoundingBox(type, accessor) {
    switch (BoundingBox[type]) {
        case 'NONE': return null;
        case 'BoundingBox2d': return accessor(new bounding_box2d_1.BoundingBox2d());
        default: return null;
    }
}
exports.unionToBoundingBox = unionToBoundingBox;
function unionListToBoundingBox(type, accessor, index) {
    switch (BoundingBox[type]) {
        case 'NONE': return null;
        case 'BoundingBox2d': return accessor(index, new bounding_box2d_1.BoundingBox2d());
        default: return null;
    }
}
exports.unionListToBoundingBox = unionListToBoundingBox;
